server.port: 8081

spring:
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/mytestdb
    username: myuser
    password: secret

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
    generate-ddl: true

logging.level:
  org.springframework.transaction:
    interceptor: trace
    transaction.support.*: debug
