name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops/github
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: '17'
      - name: Test With Gradlew
        run: ./gradlew test
