name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
env:
  DOCKER_IMAGE: hellodocker
  ECR_REPOSITORY: 276943215323.dkr.ecr.ap-northeast-2.amazonaws.com
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops/github
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: '17'
      - name: Test With Gradlew
        run: ./gradlew test
  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops/github
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .
  docker-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops/github
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: hellodocker
        run: |
          docker buildx build --platform=linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY"