name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
env:
  DOCKER_IMAGE: potenday-dev
  ECR_REPOSITORY: 276943215323.dkr.ecr.ap-northeast-2.amazonaws.com
  TARGET_HOST: kmss69052@dev.itthatcat.xyz
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops/github
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: '17'
      - name: Test With Gradlew
        run: ./gradlew test
  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops/github
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .
          echo "::set-env name=DOCKER_IMAGE_ID::${{ env.DOCKER_IMAGE }}"
